services:
  - type: web
    name: pinterest
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn pinterest_clone.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.0"
