# Generated by Django 6.0.6 on 2026-07-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='category',
            field=models.CharField(choices=[('Home decor', 'Home decor'), ('Travel', 'Travel'), ('Recipes', 'Recipes'), ('Fashion', 'Fashion'), ('Art', 'Art'), ('Fitness', 'Fitness'), ('Beauty', 'Beauty'), ('DIY & Crafts', 'DIY & Crafts'), ('Photography', 'Photography'), ('Gardening', 'Gardening'), ('Technology', 'Technology'), ('Wedding', 'Wedding'), ('Animals', 'Animals'), ('Quotes', 'Quotes'), ('Design', 'Design')], default='Home decor', max_length=50),
        ),
    ]
